export type MarketCategory = "flood" | "rain" | "storm" | "fire" | "catnat";
export type MarketType = "binary" | "threshold" | "count" | "range" | "multi";
export type MarketStatus = "open" | "closed" | "resolved_yes" | "resolved_no" | "pending";

export interface PredictionMarket {
  id: string;
  title: string;
  category: MarketCategory;
  type: MarketType;
  status: MarketStatus;
  description: string;
  resolutionRule: string;
  sourcePrimary: string;
  sourceUrl: string;
  sourceSecondary?: string;
  deadline: string; // ISO date
  createdAt: string;
  yesPrice: number; // 0-1 (probability)
  noPrice: number;
  volume: number; // EUR
  liquidity: number;
  participants: number;
  tags: string[];
  department?: string;
  coordinates?: { lat: number; lon: number };
  relatedZoneId?: string;
}

const CATEGORY_LABELS: Record<MarketCategory, string> = {
  flood: "Inondation / Crue",
  rain: "Pluie / Orage",
  storm: "Tempete / Vent",
  fire: "Feu de foret",
  catnat: "Cat Nat / Secheresse",
};

const CATEGORY_ICONS: Record<MarketCategory, string> = {
  flood: "droplets",
  rain: "cloud-rain",
  storm: "wind",
  fire: "flame",
  catnat: "file-text",
};

export { CATEGORY_LABELS, CATEGORY_ICONS };

export const MARKETS: PredictionMarket[] = [
  // ═══════════════════ INONDATION / CRUE (5) ═══════════════════
  {
    id: "MKT-001",
    title: "Au moins 1 departement en vigilance crues orange/rouge au 30 avril 2026 ?",
    category: "flood",
    type: "binary",
    status: "open",
    description: "Marche sur la presence d'au moins un departement en vigilance crues orange ou rouge en France metropolitaine.",
    resolutionRule: "Oui si la carte Vigicrues affiche au moins un territoire orange ou rouge a l'actualisation de 16h le 30/04/2026.",
    sourcePrimary: "Vigicrues — bulletin national",
    sourceUrl: "https://www.vigicrues.gouv.fr/",
    deadline: "2026-04-30T16:00:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.62,
    noPrice: 0.38,
    volume: 18400,
    liquidity: 8200,
    participants: 47,
    tags: ["vigilance", "national", "crues"],
  },
  {
    id: "MKT-002",
    title: "La Seine a Paris-Austerlitz depassera-t-elle 3.20m avant le 15 mai 2026 ?",
    category: "flood",
    type: "threshold",
    status: "open",
    description: "Marche sur le depassement du seuil de 3.20m a la station Paris-Austerlitz sur la Seine.",
    resolutionRule: "Oui si la station affiche une hauteur > 3.20m dans Hub'Eau ou Vigicrues avant le 15/05/2026 23:59.",
    sourcePrimary: "Hub'Eau hydrometrie + Vigicrues",
    sourceUrl: "https://hubeau.eaufrance.fr/page/api-hydrometrie",
    sourceSecondary: "https://www.vigicrues.gouv.fr/niv3-station.php?CdStationHydro=F700000103",
    deadline: "2026-05-15T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.28,
    noPrice: 0.72,
    volume: 31200,
    liquidity: 14500,
    participants: 89,
    tags: ["seuil", "seine", "paris", "hauteur"],
    coordinates: { lat: 48.8422, lon: 2.3654 },
  },
  {
    id: "MKT-003",
    title: "Plus de 20 communes en crue forte/tres forte sur Vigicrues Flash demain ?",
    category: "flood",
    type: "count",
    status: "open",
    description: "Marche sur le nombre de communes en risque de crue forte ou tres forte.",
    resolutionRule: "On prend le pic du nombre de communes colorees entre 06h00 et 18h00 demain. Oui si > 20.",
    sourcePrimary: "APIC / Vigicrues Flash",
    sourceUrl: "https://apic.meteo.fr/",
    deadline: "2026-04-08T18:00:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.35,
    noPrice: 0.65,
    volume: 8900,
    liquidity: 4100,
    participants: 28,
    tags: ["vigicrues-flash", "communes", "crue-soudaine"],
  },
  {
    id: "MKT-004",
    title: "Le Rhone a Beaucaire depassera-t-il 5000 m3/s avant le 31 octobre 2026 ?",
    category: "flood",
    type: "threshold",
    status: "open",
    description: "Marche sur le debit du Rhone a la station de Beaucaire.",
    resolutionRule: "Oui si le debit instantane depasse 5000 m3/s dans Hub'Eau avant l'echeance.",
    sourcePrimary: "Hub'Eau hydrometrie",
    sourceUrl: "https://hubeau.eaufrance.fr/page/api-hydrometrie",
    deadline: "2026-10-31T23:59:00+01:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.71,
    noPrice: 0.29,
    volume: 22800,
    liquidity: 10300,
    participants: 63,
    tags: ["seuil", "rhone", "debit", "beaucaire"],
    department: "30",
    coordinates: { lat: 43.8058, lon: 4.6453 },
  },
  {
    id: "MKT-005",
    title: "La Garonne a Tonneins > 8.50m avant fin juin 2026 ?",
    category: "flood",
    type: "threshold",
    status: "open",
    description: "Marche sur la hauteur de la Garonne a la station de Tonneins.",
    resolutionRule: "Oui si la hauteur depasse 8.50m dans Hub'Eau avant le 30/06/2026 23:59.",
    sourcePrimary: "Hub'Eau hydrometrie",
    sourceUrl: "https://hubeau.eaufrance.fr/page/api-hydrometrie",
    deadline: "2026-06-30T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.19,
    noPrice: 0.81,
    volume: 6700,
    liquidity: 3200,
    participants: 21,
    tags: ["seuil", "garonne", "hauteur"],
    department: "47",
  },

  // ═══════════════════ PLUIE / ORAGE (5) ═══════════════════
  {
    id: "MKT-006",
    title: "Nice enregistrera-t-elle 80mm en 24h avant dimanche 23:59 ?",
    category: "rain",
    type: "threshold",
    status: "open",
    description: "Marche sur un cumul de pluie exceptionnel a la station Meteo-France de Nice.",
    resolutionRule: "Oui si les observations Meteo-France atteignent 80mm sur une fenetre de 24h glissante.",
    sourcePrimary: "API Meteo-France observations",
    sourceUrl: "https://portail-api.meteofrance.fr/",
    deadline: "2026-04-12T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.12,
    noPrice: 0.88,
    volume: 5400,
    liquidity: 2800,
    participants: 19,
    tags: ["pluie", "nice", "seuil", "24h"],
    department: "06",
    coordinates: { lat: 43.7102, lon: 7.262 },
  },
  {
    id: "MKT-007",
    title: "Montpellier en 'precipitations tres intenses' APIC avant demain 12h ?",
    category: "rain",
    type: "binary",
    status: "open",
    description: "Marche sur le passage de Montpellier en alerte precipitations tres intenses.",
    resolutionRule: "Oui si la commune est coloree au niveau 'tres intense' sur APIC dans la fenetre.",
    sourcePrimary: "APIC",
    sourceUrl: "https://apic.meteo.fr/",
    deadline: "2026-04-08T12:00:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.08,
    noPrice: 0.92,
    volume: 3200,
    liquidity: 1600,
    participants: 12,
    tags: ["apic", "montpellier", "pluie-intense"],
    department: "34",
    coordinates: { lat: 43.6108, lon: 3.8767 },
  },
  {
    id: "MKT-008",
    title: "Plus de 3 departements en vigilance orange Orages cette semaine ?",
    category: "rain",
    type: "count",
    status: "open",
    description: "Marche sur le nombre de departements en vigilance orange pour orages.",
    resolutionRule: "Oui si au moins 3 departements sont simultanément en orange Orages sur la carte vigilance avant dimanche 23:59.",
    sourcePrimary: "Vigilance Meteo-France",
    sourceUrl: "https://vigilance.meteofrance.fr/",
    deadline: "2026-04-12T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.45,
    noPrice: 0.55,
    volume: 11600,
    liquidity: 5200,
    participants: 38,
    tags: ["vigilance", "orages", "national"],
  },
  {
    id: "MKT-009",
    title: "Cumul pluvio > 50mm sur une station du Gard cette semaine ?",
    category: "rain",
    type: "threshold",
    status: "open",
    description: "Marche sur un cumul pluviometrique significatif dans le Gard.",
    resolutionRule: "Oui si une station Meteo-France du Gard enregistre > 50mm en 24h avant dimanche 23:59.",
    sourcePrimary: "API Meteo-France",
    sourceUrl: "https://portail-api.meteofrance.fr/",
    deadline: "2026-04-12T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.31,
    noPrice: 0.69,
    volume: 7800,
    liquidity: 3600,
    participants: 24,
    tags: ["pluie", "gard", "seuil"],
    department: "30",
  },
  {
    id: "MKT-010",
    title: "Episode cevenol avant fin mai 2026 ? (vigilance rouge Pluie-Inondation)",
    category: "rain",
    type: "binary",
    status: "open",
    description: "Marche sur la survenue d'un episode cevenol majeur declenchant une vigilance rouge.",
    resolutionRule: "Oui si au moins 1 departement de l'arc cevenol (30, 34, 48, 07, 26) passe en rouge Pluie-Inondation.",
    sourcePrimary: "Vigilance Meteo-France",
    sourceUrl: "https://vigilance.meteofrance.fr/",
    deadline: "2026-05-31T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.22,
    noPrice: 0.78,
    volume: 15900,
    liquidity: 7100,
    participants: 52,
    tags: ["cevenol", "vigilance-rouge", "arc-cevenol"],
  },

  // ═══════════════════ TEMPETE / VENT (4) ═══════════════════
  {
    id: "MKT-011",
    title: "Au moins 5 departements en vigilance orange/rouge Vent violent jeudi 06h ?",
    category: "storm",
    type: "count",
    status: "open",
    description: "Marche sur le nombre de departements en alerte vent a une echeance precise.",
    resolutionRule: "Compte des departements affiches sur la carte vigilance Vent violent a 06h.",
    sourcePrimary: "Vigilance Meteo-France",
    sourceUrl: "https://vigilance.meteofrance.fr/",
    deadline: "2026-04-10T06:00:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.18,
    noPrice: 0.82,
    volume: 9200,
    liquidity: 4300,
    participants: 31,
    tags: ["vent", "vigilance", "national"],
  },
  {
    id: "MKT-012",
    title: "Le Var en vigilance orange/rouge Pluie-Inondation avant le 30/09/2026 ?",
    category: "storm",
    type: "binary",
    status: "open",
    description: "Marche sur le passage du Var en vigilance elevee pour Pluie-Inondation.",
    resolutionRule: "Oui si la carte Vigilance Meteo-France affiche le Var en orange ou rouge Pluie-Inondation avant l'echeance.",
    sourcePrimary: "Vigilance Meteo-France",
    sourceUrl: "https://vigilance.meteofrance.fr/",
    deadline: "2026-09-30T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.85,
    noPrice: 0.15,
    volume: 28700,
    liquidity: 13200,
    participants: 74,
    tags: ["var", "vigilance", "pluie-inondation"],
    department: "83",
    relatedZoneId: "ZONE-VAR-001",
  },
  {
    id: "MKT-013",
    title: "Rafale > 150 km/h enregistree en Corse avant fin 2026 ?",
    category: "storm",
    type: "threshold",
    status: "open",
    description: "Marche sur une rafale de vent extreme en Corse.",
    resolutionRule: "Oui si une station Meteo-France de Corse (2A/2B) enregistre une rafale > 150 km/h.",
    sourcePrimary: "API Meteo-France observations",
    sourceUrl: "https://portail-api.meteofrance.fr/",
    deadline: "2026-12-31T23:59:00+01:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.55,
    noPrice: 0.45,
    volume: 12400,
    liquidity: 5700,
    participants: 41,
    tags: ["vent", "rafale", "corse", "seuil"],
    department: "2A",
  },
  {
    id: "MKT-014",
    title: "Tempete nommee touchant la France metropolitaine avant le 31/03/2027 ?",
    category: "storm",
    type: "binary",
    status: "open",
    description: "Marche sur le passage d'une tempete officiellement nommee sur la France.",
    resolutionRule: "Oui si Meteo-France emet une vigilance rouge Vent violent pour une tempete nommee.",
    sourcePrimary: "Vigilance Meteo-France",
    sourceUrl: "https://vigilance.meteofrance.fr/",
    sourceSecondary: "EUMETNET / liste officielle des tempetes",
    deadline: "2027-03-31T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.78,
    noPrice: 0.22,
    volume: 41200,
    liquidity: 19800,
    participants: 112,
    tags: ["tempete", "vigilance-rouge", "national"],
  },

  // ═══════════════════ FEU DE FORET (3) ═══════════════════
  {
    id: "MKT-015",
    title: "Au moins 10 departements en rouge Meteo des forets le 15 juillet 2026 ?",
    category: "fire",
    type: "count",
    status: "open",
    description: "Marche sur le nombre de departements en danger tres eleve pour les feux.",
    resolutionRule: "Compte exact des departements en rouge sur la carte Meteo des forets du 15/07/2026.",
    sourcePrimary: "Meteo des forets",
    sourceUrl: "https://meteofrance.com/meteo-des-forets",
    deadline: "2026-07-15T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.42,
    noPrice: 0.58,
    volume: 19800,
    liquidity: 9100,
    participants: 56,
    tags: ["feu", "meteo-forets", "national", "ete"],
  },
  {
    id: "MKT-016",
    title: "EFFIS detectera-t-il un hotspot dans les Bouches-du-Rhone sous 7 jours ?",
    category: "fire",
    type: "binary",
    status: "open",
    description: "Marche sur la detection d'un feu actif par satellite dans le departement 13.",
    resolutionRule: "Oui si la couche Active Fires MODIS/VIIRS Last 7 days montre au moins 1 detection dans le 13.",
    sourcePrimary: "EFFIS / Copernicus",
    sourceUrl: "https://forest-fire.emergency.copernicus.eu/",
    sourceSecondary: "NASA FIRMS",
    deadline: "2026-04-14T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.67,
    noPrice: 0.33,
    volume: 14300,
    liquidity: 6500,
    participants: 43,
    tags: ["effis", "hotspot", "bouches-du-rhone", "firms"],
    department: "13",
    relatedZoneId: "ZONE-MRS-001",
  },
  {
    id: "MKT-017",
    title: "Zone brulee > 100 ha detectee par EFFIS dans l'Aude sous 30 jours ?",
    category: "fire",
    type: "binary",
    status: "open",
    description: "Marche sur la detection d'une zone brulee significative dans l'Aude.",
    resolutionRule: "Oui si la couche Burnt Areas MODIS VIIRS Last 30 days affiche une zone > 100ha dans le 11.",
    sourcePrimary: "EFFIS burnt areas",
    sourceUrl: "https://forest-fire.emergency.copernicus.eu/",
    deadline: "2026-05-07T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.15,
    noPrice: 0.85,
    volume: 4800,
    liquidity: 2200,
    participants: 16,
    tags: ["effis", "burnt-area", "aude", "surface"],
    department: "11",
  },

  // ═══════════════════ CAT NAT / SECHERESSE (3) ═══════════════════
  {
    id: "MKT-018",
    title: "Arrete Cat Nat inondations > 50 communes avant le 31 mai 2026 ?",
    category: "catnat",
    type: "count",
    status: "open",
    description: "Marche sur la publication d'un arrete de catastrophe naturelle pour inondations touchant plus de 50 communes.",
    resolutionRule: "Oui si un arrete publie au JO avant l'echeance concerne au moins 50 communes pour inondations/coulees de boue.",
    sourcePrimary: "Legifrance",
    sourceUrl: "https://www.legifrance.gouv.fr/",
    sourceSecondary: "Georisques",
    deadline: "2026-05-31T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.58,
    noPrice: 0.42,
    volume: 21500,
    liquidity: 9800,
    participants: 61,
    tags: ["catnat", "inondation", "arrete", "national"],
  },
  {
    id: "MKT-019",
    title: "Arrete Cat Nat secheresse/RGA pour le Gard avant le 31 aout 2026 ?",
    category: "catnat",
    type: "binary",
    status: "open",
    description: "Marche sur la reconnaissance officielle de la secheresse dans le Gard.",
    resolutionRule: "Oui si le JO publie un arrete Cat Nat secheresse/retrait-gonflement des argiles incluant le Gard.",
    sourcePrimary: "Legifrance",
    sourceUrl: "https://www.legifrance.gouv.fr/",
    sourceSecondary: "Georisques",
    deadline: "2026-08-31T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.44,
    noPrice: 0.56,
    volume: 8900,
    liquidity: 4100,
    participants: 29,
    tags: ["catnat", "secheresse", "rga", "gard"],
    department: "30",
  },
  {
    id: "MKT-020",
    title: "Plus de 200 communes reconnues Cat Nat au S1 2026 ?",
    category: "catnat",
    type: "count",
    status: "open",
    description: "Marche sur le nombre total de communes reconnues en Cat Nat au premier semestre 2026.",
    resolutionRule: "Oui si le cumul des communes dans les arretes Cat Nat publies entre le 01/01 et le 30/06/2026 depasse 200.",
    sourcePrimary: "Legifrance + Georisques",
    sourceUrl: "https://www.georisques.gouv.fr/",
    deadline: "2026-06-30T23:59:00+02:00",
    createdAt: "2026-04-07T10:00:00Z",
    yesPrice: 0.72,
    noPrice: 0.28,
    volume: 16300,
    liquidity: 7400,
    participants: 48,
    tags: ["catnat", "communes", "national", "s1"],
  },
];
